version: '3'
services:

  server:
    image: 'flhe:server'
    container_name: fl_server
    environment:
      - SERVER_IP=0.0.0.0:9999
      - NCLIENTS=10
      - NUM_ROUNDS=100
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - FRAC_FIT=0.5
      - DIRICHLET_ALPHA=0.1
    volumes:
      - ./server:/server:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    

  client-0:
    image: 'flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=0
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - NIID=True
      - NCLIENTS=10
      - DIRICHLET_ALPHA=0.1
      - START2SHARE=1
      - PERCENTAGE=0.3
      - TECHNIQUE=robin_round
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-1:
    image: 'flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=1
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - NIID=True
      - NCLIENTS=10
      - DIRICHLET_ALPHA=0.1
      - START2SHARE=1
      - PERCENTAGE=0.3
      - TECHNIQUE=robin_round
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-2:
    image: 'flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=2
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - NIID=True
      - NCLIENTS=10
      - DIRICHLET_ALPHA=0.1
      - START2SHARE=1
      - PERCENTAGE=0.3
      - TECHNIQUE=robin_round
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-3:
    image: 'flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=3
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - NIID=True
      - NCLIENTS=10
      - DIRICHLET_ALPHA=0.1
      - START2SHARE=1
      - PERCENTAGE=0.3
      - TECHNIQUE=robin_round
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-4:
    image: 'flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=4
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - NIID=True
      - NCLIENTS=10
      - DIRICHLET_ALPHA=0.1
      - START2SHARE=1
      - PERCENTAGE=0.3
      - TECHNIQUE=robin_round
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-5:
    image: 'flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=5
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - NIID=True
      - NCLIENTS=10
      - DIRICHLET_ALPHA=0.1
      - START2SHARE=1
      - PERCENTAGE=0.3
      - TECHNIQUE=robin_round
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-6:
    image: 'flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=6
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - NIID=True
      - NCLIENTS=10
      - DIRICHLET_ALPHA=0.1
      - START2SHARE=1
      - PERCENTAGE=0.3
      - TECHNIQUE=robin_round
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-7:
    image: 'flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=7
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - NIID=True
      - NCLIENTS=10
      - DIRICHLET_ALPHA=0.1
      - START2SHARE=1
      - PERCENTAGE=0.3
      - TECHNIQUE=robin_round
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-8:
    image: 'flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=8
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - NIID=True
      - NCLIENTS=10
      - DIRICHLET_ALPHA=0.1
      - START2SHARE=1
      - PERCENTAGE=0.3
      - TECHNIQUE=robin_round
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-9:
    image: 'flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=9
      - SOLUTION=FedPHE
      - DATASET=MNIST
      - NIID=True
      - NCLIENTS=10
      - DIRICHLET_ALPHA=0.1
      - START2SHARE=1
      - PERCENTAGE=0.3
      - TECHNIQUE=robin_round
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

