version: '3'
services:

  server:
    image: 'allanmsouza/flhe:server'
    container_name: fl_server
    environment:
      - SERVER_IP=0.0.0.0:9999
      - NCLIENTS=2
      - NUM_ROUNDS=50
      - SOLUTION_NAME=FLHE
      - DATASET=CIFAR10
      - FRAC_FIT=0.2
      - DIRICHLET_ALPHA=0.5
      - HOMOMORPHIC=True
      - PACKING=True
      - ONLYSUM=True
    volumes:
      - ./server:/server:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    

  client-0:
    image: 'allanmsouza/flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=0
      - SOLUTION_NAME=FLHE
      - DATASET=CIFAR10
      - NIID=True
      - NCLIENTS=2
      - DIRICHLET_ALPHA=0.5
      - START2SHARE=2
      - HOMOMORPHIC=True
      - PACKING=True
      - HOMOMORPHIC_TYPE=Full
      - ONLYSUM=True
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

  client-1:
    image: 'allanmsouza/flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=1
      - SOLUTION_NAME=FLHE
      - DATASET=CIFAR10
      - NIID=True
      - NCLIENTS=2
      - DIRICHLET_ALPHA=0.5
      - START2SHARE=2
      - HOMOMORPHIC=True
      - PACKING=True
      - HOMOMORPHIC_TYPE=Full
      - ONLYSUM=True
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

