version: '3.8'
services:

  server:
    image: 'allanmsouza/flhe:server'
    container_name: fl_server
    environment:
      - SERVER_IP=0.0.0.0:9999
      - NCLIENTS=2
      - NUM_ROUNDS=50
      - SOLUTION_NAME=teste
      - DATASET=mnist
      - FRAC_FIT=1
      - DIRICHLET_ALPHA=0.2
    volumes:
      - ./server:/server:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    

  client-0:
    image: 'allanmsouza/flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=0
      - SOLUTION_NAME=teste
      - DATASET=mnist
      - NIID=False
      - NCLIENTS=2
      - DIRICHLET_ALPHA=0.7
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
        
  client-1:
    image: 'allanmsouza/flhe:client'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=1
      - SOLUTION_NAME=teste
      - DATASET=mnist
      - NIID=False
      - NCLIENTS=2
      - DIRICHLET_ALPHA=0.7
    volumes:
      - ./client:/client:r
      - ./context:/context:r
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          

