version: '3'
services:

  server:
    image: 'flhe:server'
    container_name: fl_server
    environment:
      - SERVER_IP=0.0.0.0:9999
      - NCLIENTS=4
      - NUM_ROUNDS=100
      - SOLUTION_NAME=teste_rasp
      - DATASET=CIFAR10
      - FRAC_FIT=1
      - DIRICHLET_ALPHA=1
      - HOMOMORPHIC=False
    volumes:
      - /opt/nodes/FLHE/logs:/logs:rw
      - /opt/nodes/FLHE/server:/server:rw
      - /opt/nodes/FLHE/context:/context:r
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    

  client-0:
    image: 'teste_tenseal:latest'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=0
      - SOLUTION_NAME=teste_rasp
      - DATASET=CIFAR10
      - NIID=True
      - NCLIENTS=4
      - DIRICHLET_ALPHA=1
      - START2SHARE=1
      - HOMOMORPHIC=False
      - HOMOMORPHIC_TYPE=Full
    volumes:
      - vol_logs:/TenSEAL/logs:rw
      - vol_client:/TenSEAL/client:r
      - vol_context:/context:r
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
    command: python client/client.py
          

  client-1:
    image: 'teste_tenseal:latest'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=1
      - SOLUTION_NAME=teste_rasp
      - DATASET=CIFAR10
      - NIID=True
      - NCLIENTS=4
      - DIRICHLET_ALPHA=1
      - START2SHARE=1
      - HOMOMORPHIC=False
      - HOMOMORPHIC_TYPE=Full
    volumes:
      - vol_logs:/TenSEAL/logs:rw
      - vol_client:/TenSEAL/client:r
      - vol_context:/context:r
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
    command: python client/client.py
          

  client-2:
    image: 'teste_tenseal:latest'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=2
      - SOLUTION_NAME=teste_rasp
      - DATASET=CIFAR10
      - NIID=True
      - NCLIENTS=4
      - DIRICHLET_ALPHA=1
      - START2SHARE=1
      - HOMOMORPHIC=False
      - HOMOMORPHIC_TYPE=Full
    volumes:
      - vol_logs:/TenSEAL/logs:rw
      - vol_client:/TenSEAL/client:r
      - vol_context:/context:r
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
    command: python client/client.py
          

  client-3:
    image: 'teste_tenseal:latest'
    environment:
      - SERVER_IP=fl_server:9999
      - CID=3
      - SOLUTION_NAME=teste_rasp
      - DATASET=CIFAR10
      - NIID=True
      - NCLIENTS=4
      - DIRICHLET_ALPHA=1
      - START2SHARE=1
      - HOMOMORPHIC=False
      - HOMOMORPHIC_TYPE=Full
    volumes:
      - vol_logs:/TenSEAL/logs:rw
      - vol_client:/TenSEAL/client:r
      - vol_context:/context:r
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
    command: python client/client.py
          

volumes:
  vol_logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.113,nolock,soft,rw
      device: :/opt/nodes/FLHE/logs
      
  vol_client:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.113,nolock,soft,rw
      device: :/opt/nodes/FLHE/client
      
  vol_server:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.113,nolock,soft,rw
      device: :/opt/nodes/FLHE/server
      
  vol_context:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.113,nolock,soft,rw
      device: :/opt/nodes/FLHE/context
  

